
[wrk]
threads=10
thread_connections=10
latency=true
duration="10s"

[[apis]]
name="get"
desc="Get 请求"
path="/api/get"
method="GET"
body=""

    [[apis.params]]
    name="param-1"
    value="param-1-value"

    [[apis.params]]
    name="param-2"
    value="param-2-value"
